--
-- Copyright (c) 2013 SLL. <http://sll.se>
--
-- This file is part of Invoice-Data.
--
--     Invoice-Data is free software: you can redistribute it and/or modify
--     it under the terms of the GNU Lesser General Public License as published by
--     the Free Software Foundation, either version 3 of the License, or
--     (at your option) any later version.
--
--     Invoice-Data is distributed in the hope that it will be useful,
--     but WITHOUT ANY WARRANTY; without even the implied warranty of
--     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
--     GNU Lesser General Public License for more details.
--
--     You should have received a copy of the GNU Lesser General Public License
--     along with Invoice-Data.  If not, see <http://www.gnu.org/licenses/lgpl.txt>.
--

-- 
-- Creation script for H2 Embedded Database  
--

create table invoice_data (
	id bigint generated by default as identity, 
	created_by varchar(64) not null, 
	created_timestamp timestamp not null, 
	supplier_id varchar(64) not null, 
	primary key (id)
);

create index invoice_data_event_query_index on invoice_data_event (supplier_id, pending);

 create table invoice_data_event (
        credit boolean not null,
        id varchar(64) not null,
        created_timestamp timestamp not null,
        end_timestamp timestamp not null,
        payment_responsible varchar(64) not null,
        pending boolean,
        service_code varchar(64) not null,
        signed_by varchar(64) not null,
        signed_timestamp timestamp not null,
        start_timestamp timestamp not null,
        supplier_id varchar(64) not null,
        supplier_name varchar(256) not null,
        invoice_data_id bigint,
        primary key (credit, id)
    );

alter table invoice_data_event add constraint fk_invoice_data_id foreign key (invoice_data_id) references invoice_data;

    create table invoice_data_event_item (
        id bigint generated by default as identity,
        description varchar(256) not null,
        item_id varchar(64) not null,
        price decimal(8,2),
        qty decimal(8,2),
        event_credit boolean not null,
        event_id varchar(64) not null,
        primary key (id)
    );

alter table invoice_data_event_item
 add constraint fk_invoice_data_event
        foreign key (event_credit, event_id)
        references invoice_data_event;

-- Test data

insert into invoice_data (created_by, created_timestamp, supplier_id)
values ('test-script', current_timestamp, 'supplier-1');





